language: java, node_js
jdk:
  - oraclejdk8
sudo: false
before_install:
  - nvm install 4.4.0
  - node --version
  - npm install -g bower
addons:
  apt:
    packages:
    - php5-dev
    - php5-cli
    - php-pear
