
spring:
    thymeleaf:
        mode: XHTML
        cache: true
    messageSource:
        cacheSeconds: 1

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache.timeToLiveSeconds: 3600

# Disable the spring security default configuration from spring-boot-actuator
#management.security.enabled: false

# Disable all endpoints
endpoints.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
#jhipster.security.rememberme.key: agate

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

authentication:
    oauth:
        clientid: jhipsterapp
        secret: mySecretOAuthSecret
# Token is valid 30 minutes
        tokenValidityInSeconds: 1800