# used for developement when application is run with dev profile
server:
    port: 8081
    address: localhost

https:
    port: 8444

spring:
    profiles: dev

    data:
        mongodb:
          host: localhost
          port: 27017
          database: agate

    thymeleaf:
        mode: XHTML
        cache: false

    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        from: no-reply@obiba.org

    messageSource:
        cacheSeconds: 1

shiro:
  password:
    nbHashIterations: 10000
    salt: agate

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600

# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: org.obiba.agate
      domain: org.obiba.agate.domain
      restdto: org.obiba.agate.web.rest.dto
    liquibase:
      defaultCatalogName:
      defaultSchema:
    watchdir:
      - target/classes

# security configuration (this key should be unique for your application, and kept secret)
#jhipster.security.rememberme.key: agate

endpoints.health.sensitive: false

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

authentication:
    oauth:
        clientid: jhipsterapp
        secret: mySecretOAuthSecret
        # Token is valid 30 minutes
        tokenValidityInSeconds: 1800

registration:
    pendingForApprovalSubject: Account Registration
    pendingForReviewSubject: Registration Pending
    confirmationSubject: Registration Approved
    resetPasswordSubject: Password Reset

recaptcha:
    verifyUrl: https://www.google.com/recaptcha/api/siteverify
    secret: 6Lfo7gYTAAAAADym-vSDvPBeBCXaxIprA0QXLk_b

client:
    reCaptchaKey: 6Lfo7gYTAAAAAOyl8_MHuH-AVBzRDtpIuJrjL3Pb
